[workspace.package]
authors = ["Antonius Naumann"]
edition = "2021"
version = "0.0.0"

[workspace]
resolver = "2"
members = [
  "galvan-ast",
  "galvan-core",
  "galvan-files",
  "galvan-pest",
  "galvan-transpiler",
  "galvan-test-macro",
]