[package]
name = "galvan-transpiler"
authors.workspace = true
edition.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.10.2"

galvan-files = { path = "../galvan-files" }
galvan-ast = { path = "../galvan-ast" }

[dev-dependencies]
galvan-test-macro = { path = "../galvan-test-macro" }

[features]
exec = ["galvan-files/exec"]

[[bin]]
name = "galvan-transpile"
required-features = ["exec"]
path = "src/main.rs"
