[package]
name = "galvan-transpiler"
authors.workspace = true
edition.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2.4.0"

galvan-parser = { path = "../galvan-parser" }
