[package]
name = "galvan-transpiler"
authors.workspace = true
edition.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = { version = "2.4.0", optional = true }

galvan-ast = { path = "../galvan-ast" }
regex = "1.10.2"

[dev-dependencies]
galvan-test-macro = { path = "../galvan-test-macro" }

[features]
exec = ["dep:walkdir"]

[[bin]]
name = "galvan-transpile"
required-features = ["exec"]
path = "src/main.rs"
