[package]
name = "galvan-macro"
authors.workspace = true
edition.workspace = true
version.workspace = true

[lib]
proc-macro = true

[dependencies]
syn = "2.0"
quote = "1.0"
proc-macro2 = "1.0"

galvan-lexer = { path = "../galvan-lexer" }
